title: Blogs
author: Bhavesh Prajapati
email: info@bhaveshpp.com
description: > # this means to ignore newlines until "baseurl:"
  This is bhavesh prajapati's blogs, it help you to get knowledge about new technology in 
  web and e-commerce developments. thanks for visit :).

# social links
twitter_username: bhaveshpp111 # DO NOT include the @ character, or else the build will fail!
github_username:  bhaveshpp # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
